version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: scipy
    versions:
    - 1.6.0
    - 1.6.1
    - 1.6.2
  - dependency-name: reportlab
    versions:
    - 3.5.60
    - 3.5.62
    - 3.5.63
    - 3.5.64
    - 3.5.65
    - 3.5.66
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: fs
    versions:
    - 2.4.12
  - dependency-name: zopfli
    versions:
    - 0.1.7
  - dependency-name: sphinx-rtd-theme
    versions:
    - 0.5.1
  - dependency-name: munkres
    versions:
    - 1.1.4
